model_name: auto_assign_1_10

data:
  train_annotation_path: /home/wangchao/public_dataset/coco/annotations/instances_val2017.json
  val_annotation_path: /home/wangchao/public_dataset/coco/annotations/instances_val2017.json
  train_img_root: /home/wangchao/public_dataset/coco/images/val2017
  val_img_root: /home/wangchao/public_dataset/coco/images/val2017
  img_size: 768
  use_crowd: False
  batch_size: 16
  num_workers: 8
  debug: False
  remove_blank: Ture

model:
  num_cls: 80
  strides: [8, 16, 32, 64, 128]
  backbone: resnet18
  freeze_bn: False

hyper_params:
  alpha: 0.25
  gamma: 2.0
  multi_scale: [768]
  iou_type: giou

optim:
  optimizer: SGD
  lr: 0.01
  momentum: 0.9
  milestones: [18,24]
  alpha: 0.1
  warm_up_epoch: 1
  weight_decay: 0.0001
  epochs: 25
  sync_bn: True

val:
  interval: 1
  weight_path: weights
  conf_thresh: 0.05
  iou_thresh: 0.5
  max_det: 300

gpus: '0'